CREATE TABLE Contacts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Type VARCHAR(50) CHECK (Type IN ('Phone Number', 'Email')) NOT NULL,
    PhoneNumber VARCHAR(25),
    Email VARCHAR(150),
    PersonId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (PersonId) REFERENCES Persons(Id) ON DELETE CASCADE,
);