CREATE TABLE NaturalPersons (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FirstName VARCHAR(80) NOT NULL,
    FirstSurname VARCHAR(80) NOT NULL,
    SecondSurname VARCHAR(80) NOT NULL,
    UserId UNIQUEIDENTIFIER NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (Id) REFERENCES Persons(Id) ON DELETE CASCADE
);