CREATE TABLE Payrolls (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    PayrollManagerId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (CompanyId) REFERENCES Companies(Id),
    FOREIGN KEY (PayrollManagerId) REFERENCES PayrollManagers(Id) ON DELETE CASCADE
);