USE PayrollSystem

CREATE TABLE PaymentDetails (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	PayrollId UNIQUEIDENTIFIER,
	EmployeeId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (PayrollId) REFERENCES Payrolls(Id),
	FOREIGN KEY (EmployeeId) REFERENCES Employees(Id),
);