CREATE TABLE Employers (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    WorkerId AS (CAST('EMPLOYER-' + CAST(Id AS VARCHAR(36)) AS VARCHAR(80))) PERSISTED UNIQUE,
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (CompanyId) REFERENCES Companies(Id) ON DELETE NO ACTION,
    FOREIGN KEY (Id) REFERENCES NaturalPersons(Id) ON DELETE CASCADE
);