CREATE TABLE EmployeeXBenefit (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	BenefitId UNIQUEIDENTIFIER NOT NULL,
	EmployeeId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (BenefitId) REFERENCES Benefits(Id),
	FOREIGN KEY (EmployeeId) REFERENCES Employees(Id),
);