CREATE TABLE Payrolls (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    PayrollManagerId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (CompanyId) REFERENCES Companies(Id) ON DELETE CASCADE,
    FOREIGN KEY (PayrollManagerId) REFERENCES PayrollManagers(Id)
);