CREATE TABLE Timesheets (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    EmployeeId UNIQUEIDENTIFIER NOT NULL,
    PayrollId UNIQUEIDENTIFIER,
    FOREIGN KEY (EmployeeId) REFERENCES Employees(Id),
    FOREIGN KEY (PayrollId) REFERENCES Payrolls(Id) ON DELETE SET NULL
)