CREATE TABLE Days (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Date DATE NOT NULL,
    HoursWorked INT,
    WorkDescription VARCHAR(300),
    IsApproved BIT NOT NULL DEFAULT 0,
    TimesheetId UNIQUEIDENTIFIER NOT NULL,
    SupervisorId UNIQUEIDENTIFIER,	
    FOREIGN KEY (TimesheetId) REFERENCES Timesheets(Id) ON DELETE CASCADE,
    FOREIGN KEY (SupervisorId) REFERENCES Supervisors(Id)
)