USE PayrollSystem

CREATE TABLE APIParameters (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(35) NOT NULL,
    Type VARCHAR(15) 
       NOT NULL 
       CHECK (Type IN ('UserDefined', 'SystemDefined')),
	APIId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (APIId) REFERENCES APIs(Id)
);


